### ISSUE TITLE
Test file path not included in ctest's test name

### ISSUE THREAD

**Issue by djungelorm** [python-cmake/pytest-cmake#43]
Would it be possible to include the test's file path in the test name? Currently, if you have test functions with the same name in different files, the resulting test name in ctest is identical.

For example, consider the following file hierarchy:
```
__init__.py
one/__init__.py
one/test_a.py
one/test_b.py
two/__init__.py
two/test_a.py
two/test_b.py
```
where each `test_*.py` file contains a single test function called `test`. The output of running vanilla pytest on this is:
```
one/test_a.py::test PASSED
one/test_b.py::test PASSED
two/test_a.py::test PASSED
two/test_b.py::test PASSED
```

Using pytest-cmake using `pytest_discover_tests(PythonTests)` I get the following:
```
    Start 1: PythonTests.test
1/4 Test #1: PythonTests.test .................   Passed    0.08 sec
    Start 2: PythonTests.test
2/4 Test #2: PythonTests.test .................   Passed    0.08 sec
    Start 3: PythonTests.test
3/4 Test #3: PythonTests.test .................   Passed    0.08 sec
    Start 4: PythonTests.test
4/4 Test #4: PythonTests.test .................   Passed    0.08 sec
```

All the tests have the same name!

Something like the following would be ideal. This takes the file path reported by pytest, removes the `.py` extension and replaces forward slashes with periods, then includes it in the test name. If you want to maintain previous behaviour by default, we could put this behind an option.
```
    Start 1: PythonTests.one.test_a.test
1/4 Test #1: PythonTests.one.test_a.test ......   Passed    0.08 sec
    Start 2: PythonTests.one.test_b.test
2/4 Test #2: PythonTests.one.test_b.test ......   Passed    0.08 sec
    Start 3: PythonTests.two.test_a.test
3/4 Test #3: PythonTests.two.test_a.test ......   Passed    0.08 sec
    Start 4: PythonTests.two.test_b.test
4/4 Test #4: PythonTests.two.test_b.test ......   Passed    0.07 sec
```

**Comment by buddly27** [comment]
How about adding an option to include the test file in the identifier, similar to how Pytest organizes its test collection?

```
    Start 1: one/test_a.py::PythonTests.test
1/4 Test #1: one/test_a.py::PythonTests.test ......   Passed    0.08 sec
    Start 2: one/test_b.py::PythonTests.test
2/4 Test #2: one/test_b.py::PythonTests.test ......   Passed    0.08 sec
    Start 3: two/test_a.py::PythonTests.test
3/4 Test #3: two/test_a.py::PythonTests.test ......   Passed    0.08 sec
    Start 4: two/test_b.py::PythonTests.test
4/4 Test #4: two/test_b.py::PythonTests.test ......   Passed    0.07 sec
```

This would also work well with ctest -R since there are no regex symbols to escape.

**Comment by djungelorm** [comment]
I'd prefer if the test group name came first, as in my head that logically groups all the test files together. I see the hierarchy as: test group, test file, test function -- so would be good if the test name followed the same order.

To give a concrete example, in my project I have tests like the following (note: I can't really link to it as it's in a private repo):

Cmake config looks like:
```
pytest_discover_tests(
  csim_computer
  DEPENDS biscuit-sim
  TRIM_FROM_NAME "(_test)|(test_)"
  STRIP_PARAM_BRACKETS
  ENVIRONMENT
    "CMAKE_BINARY_DIR=${CMAKE_BINARY_DIR}"
)

pytest_discover_tests(
  vsim_computer
  DEPENDS biscuit-sim
  TRIM_FROM_NAME "(_test)|(test_)"
  STRIP_PARAM_BRACKETS
  ENVIRONMENT
    "CMAKE_BINARY_DIR=${CMAKE_BINARY_DIR}"
    "BISCUIT_SIM_HARDWARE=1"
)
```
The test files look like:
```
sim/test/computer/CMakeLists.txt     <--- as above
sim/test/computer/test_move.py
sim/test/computer/test_jump.py
...
```

I'd like the test names to look like:
```
...
          Start 1090: csim_computer.move.no_carry_before_ml_overflows
 155/2123 Test #2109: vsim_computer.move.memory_indirect_to_register.r10 .......................   Passed    0.48 sec
          Start 1532: vsim_computer.jump.external_interrupt_rti_from_0x0100
 156/2123 Test #1306: vsim_computer.calc.add_from_immediate_to_memory_indirect.40-0-40-0-0 .....   Passed    0.45 sec
          Start 1101: vsim_computer.calc.add.253-17-14-1-0
...
```

I don't mind if the test names are something like `PythonTests.one/test_a.py::test` by default, but would like to have an option to rewrite the `::`, `.py`, `/` and `test_` to obtain `PythonTests.one.a.test`

`TRIM_FROM_NAME` I don't think would be sufficient to do this. Would need something more general like `REPLACE_IN_NAME` that you proposed in https://github.com/python-cmake/pytest-cmake/issues/41

**Comment by buddly27** [comment]
Ah true, the target name should be first indeed. Then, we could add an option to extract the path hierarchy to compute the identifier. I just pushed a quick test on this PR: https://github.com/python-cmake/pytest-cmake/pull/44

Ley me know what you think!
